"""Installation file for the ansys-api-speos package"""

import os
from datetime import datetime

import setuptools

from ansys.tools.protoc_helper import create_cmdclass_override

# Get the long description from the README file
HERE = os.path.abspath(os.path.dirname(__file__))
with open(os.path.join(HERE, "README.md"), encoding="utf-8") as f:
    long_description = f.read()

product = "speos"
library = ""
package_info = ["ansys", "api", product, library, ""]
with open(os.path.join(HERE, "src", "py", "utils", "ansys", "api", product, library, "VERSION"), encoding="utf-8") as f:
    version = f.read().strip()

package_name = "ansys-api-speos"
dot_package_name = '.'.join(filter(None, package_info))

description = f"Autogenerated python gRPC interface package for {package_name}, built on {datetime.now().strftime('%H:%M:%S on %d %B %Y')}"

# We need to search for packages in both 'src/py/utils' and 'src/protos', because some
# of the package names don't exist in 'src/py/utils'. The generation of Python files
# from '.proto' files happens only _after_ the package list is generated.
packages = set(setuptools.find_namespace_packages("src/py/utils", include=("ansys.*",)))
packages.update(setuptools.find_namespace_packages("src/protos", include=("ansys.*",)))
packages = list(packages)

if __name__ == "__main__":
    setuptools.setup(
        name=package_name,
        version=version,
        author="ANSYS, Inc.",
        author_email='support@ansys.com',
        description=description,
        long_description=long_description,
        long_description_content_type='text/markdown',
        url=f"https://github.com/ansys/{package_name}",
        license="MIT",
        python_requires=">=3.8",
        install_requires=["grpcio~=1.48", "protobuf~=3.20"],
        package_dir = {"": "src/py/utils"},
        packages=packages,
        package_data={
            "": ["*.proto", "*.pyi", "py.typed", "VERSION"],
        },
        entry_points={
            "ansys.tools.protoc_helper.proto_provider": [
                f"{dot_package_name}={dot_package_name}"
            ],
        },
        cmdclass=create_cmdclass_override(proto_directories=["src/protos"])
    )
